### ISSUE TITLE
运行之后崩溃

### ISSUE THREAD

**Issue by Object0220** [fanqieVip/AndroidOcrLibs#4]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fanjun.orclibs, PID: 18484
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.fanjun.orclibs-AqbIkDkEWCkuuuDjpCIJjg==/base.apk"],nativeLibraryDirectories=[/data/app/com.fanjun.orclibs-AqbIkDkEWCkuuuDjpCIJjg==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libpnocrengine.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at hotcard.doc.reader.NativeOcrPn.<clinit>(NativeOcrPn.java:15)
        at com.fanjun.orclibs.ScanCarActivity.onStart(ScanCarActivity.java:58)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
        at android.app.Activity.performStart(Activity.java:7924)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3328)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/MQSEventManagerDelegate: failed to get MQSService.

**Comment by fanqieVip** [comment]
//配置里面加上这个
defaultConfig {
        ......

        ndk {
            // 设定支持的架构
            abiFilters "armeabi"
        }
    }

**Comment by Object0220** [comment]
谢谢大佬，大佬牛逼 哈哈哈哈

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: fanqieVip <notifications@github.com>
发送时间: Friday, January 3, 2020 2:34:08 PM
收件人: fanqieVip/AndroidOcrLibs <AndroidOcrLibs@noreply.github.com>
抄送: 风花雪月的米 <qi022000@outlook.com>; Author <author@noreply.github.com>
主题: Re: [fanqieVip/AndroidOcrLibs] 运行之后崩溃 (#4)


//配置里面加上这个
defaultConfig {
......

    ndk {

        // 设定支持的架构

        abiFilters "armeabi"

    }

}



―

**Comment by fanqieVip** [comment]
不客气。如果需要更多的识别sdk，可以跟我留言哦
